spring.application.name=cart-checkout-service
server.port=8080


spring.datasource.url=jdbc:h2:mem:ecommercedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


mock.payment.webhook-url=http://localhost:8080/payments/webhook
mock.payment.delay-ms=2000


logging.level.com.ecommerce=DEBUG
